DROP TRIGGER IF EXISTS NewCheckIn on ChecksIn;
DROP TRIGGER IF EXISTS NewTip on Tip;
DROP TRIGGER IF EXISTS UpdateTipLikes on Tip;
DROP FUNCTION IF EXISTS UpdateTipLikeCount;
DROP FUNCTION IF EXISTS UpdateTipCount;
DROP FUNCTION IF EXISTS incTip;